# Generated by Django 5.1.5 on 2025-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='titlo',
            new_name='titulo',
        ),
    ]
