# Generated by Django 5.1.5 on 2025-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='titulo_list',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
