# Generated by Django 5.1.7 on 2025-03-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_todo_status_alter_todo_titulo_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='titulo',
            new_name='titlo',
        ),
    ]
