# Generated by Django 5.1.7 on 2025-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('velo_max', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.CharField(max_length=255)),
                ('classificacao', models.CharField(max_length=255)),
                ('time', models.CharField(choices=[('Apn', 'Alpine'), ('Wls', 'Williams'), ('Frr', 'Ferrari'), ('Hss', 'Hass'), ('Amg', 'Mercedes'), ('Rbr', 'Red Bull'), ('Vrb', 'Racing Bulls'), ('Sbr', 'Sauber'), ('Mcl', 'McLaren'), ('AsM', 'Aston Martin')], max_length=10)),
            ],
        ),
    ]
