# Generated by Django 5.1.7 on 2025-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='classificacao',
            field=models.PositiveIntegerField(),
        ),
    ]
