# Generated by Django 5.1.7 on 2025-03-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=255)),
                ('name_factory', models.CharField(max_length=255)),
                ('horsepower', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('qty_ports', models.PositiveIntegerField()),
                ('qty_roads', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('fuel', models.CharField(choices=[('gs', 'Gasoline'), ('gnv', 'Compressed Natural Gas'), ('al', 'Ethanol'), ('ev', 'Electric'), ('ds', 'Diesel'), ('bd', 'Biodiesel'), ('bs', 'Biofuel')], max_length=9)),
            ],
        ),
    ]
