# Generated by Django 5.1.7 on 2025-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariods16',
            name='edv',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
